/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#131318",
        "on-secondary-fixed-variant": "#095300",
        "on-surface-variant": "#c2c6d8",
        "outline-variant": "#424656",
        "surface-tint": "#b3c5ff",
        "inverse-primary": "#0054d6",
        "on-tertiary-container": "#f8f8f8",
        "background": "#131318",
        "tertiary-container": "#707272",
        "outline": "#8c90a1",
        "surface": "#131318",
        "on-primary-container": "#f8f7ff",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "primary-container": "#0066ff",
        "secondary-fixed-dim": "#2ae500",
        "surface-bright": "#39383e",
        "primary": "#b3c5ff",
        "surface-container": "#1f1f25",
        "secondary-fixed": "#79ff5b",
        "tertiary-fixed": "#e2e2e2",
        "on-background": "#e4e1e9",
        "on-secondary-container": "#0f6d00",
        "secondary": "#d7ffc5",
        "on-primary-fixed-variant": "#003fa4",
        "surface-container-high": "#2a292f",
        "primary-fixed": "#dae1ff",
        "on-secondary": "#053900",
        "surface-container-highest": "#35343a",
        "on-primary-fixed": "#001849",
        "inverse-on-surface": "#303036",
        "on-secondary-fixed": "#022100",
        "error-container": "#93000a",
        "tertiary": "#c6c6c7",
        "on-tertiary-fixed-variant": "#454747",
        "on-tertiary": "#2f3131",
        "on-error": "#690005",
        "secondary-container": "#2ff801",
        "tertiary-fixed-dim": "#c6c6c7",
        "primary-fixed-dim": "#b3c5ff",
        "inverse-surface": "#e4e1e9",
        "surface-variant": "#35343a",
        "surface-container-low": "#1b1b20",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-container-lowest": "#0e0e13",
        "on-primary": "#002b75",
        "on-surface": "#e4e1e9"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "40px",
        "margin-desktop": "48px",
        "md": "24px",
        "xl": "64px",
        "base": "8px",
        "sm": "12px",
        "gutter": "16px",
        "margin-mobile": "20px",
        "xs": "4px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"]
      }
    },
  },
  plugins: [],
}
